In [69]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [70]:
chestx = pd.read_csv("../reports/chestx/layer/predictions_per_layer_test.csv")
padchest = pd.read_csv("../reports/padchest/layer/predictions_per_layer_test.csv")
padchest_px = pd.read_csv("../reports/padchest_px/layer/predictions_per_layer_test.csv")

# ChestX-ray14

In [71]:
chestx["prob"] = chestx["layer_17"]
chestx["dist_from_05"] = (chestx["prob"] - 0.5).abs()

cols = ["img_id", "y_true", "drain", "sex", "prob"]

no_disease = chestx.nsmallest(6, "prob")[cols] # closest to 0 = confident no pneumothorax
disease = chestx.nlargest(5, "prob")[cols] # closest to 1 = confident pneumothorax
uncertain = chestx.nsmallest(5, "dist_from_05")[cols] # closest to 0.5 = uncertain

print("most confident: NO pneumothorax (prob. closest to 0)")
print(no_disease)

print("most confident: pneumothorax (prob. closest to 1)")
print(disease)

print("least confident (prob. closest to 0.5)")
print(uncertain)

# no disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/ChestX-ray14/images/{00010007_121.png,00020945_039.png,00030450_001.png,00013377_010.png,00030450_002.png,00017318_015.png} ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/chestx/confidence_images/no_disease

# disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/ChestX-ray14/images/{00016568_023.png,00013111_057.png,00022707_012.png,00022707_011.png,00022726_006.png} ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/chestx/confidence_images/disease

# uncertain
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/ChestX-ray14/images/{00018387_027.png,00000830_000.png,00007557_017.png,00011514_012.png,00004822_012.png} ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/chestx/confidence_images/uncertain

most confident: NO pneumothorax (prob. closest to 0)
                 img_id  y_true  drain sex      prob
6366   00010007_121.png       0      1   M  0.033020
17897  00020945_039.png       0      0   M  0.072429
25220  00030450_001.png       0      1   M  0.073807
9721   00013377_010.png       0      0   F  0.074388
25221  00030450_002.png       0      1   M  0.080587
14575  00017318_015.png       0      0   M  0.081543
most confident: pneumothorax (prob. closest to 1)
                 img_id  y_true  drain sex      prob
13660  00016568_023.png       1      1   F  0.999564
9297   00013111_057.png       0      1   M  0.999554
19193  00022707_012.png       0      1   F  0.999504
19192  00022707_011.png       0      1   F  0.999477
19216  00022726_006.png       1      1   F  0.999469
least confident (prob. closest to 0.5)
                 img_id  y_true  drain sex      prob
15661  00018387_027.png       0      1   M  0.500001
673    00000830_000.png       0      0   F  0.500005
4628   00007557_017.png       0      1   M  0.499990
7703   00011514_012.png       0      1   M  0.500026
2941   00004822_012.png       0      1   M  0.500028

# PadChest (cardiomegaly)

In [72]:
padchest["prob"] = padchest["layer_17"]
padchest["dist_from_05"] = (padchest["prob"] - 0.5).abs()

cols = ["img_id", "y_true", "scanner", "sex", "prob"]

no_disease = padchest.nsmallest(5, "prob")[cols] # closest to 0 = confident no pneumothorax
disease = padchest.nlargest(5, "prob")[cols] # closest to 1 = confident pneumothorax
uncertain = padchest.nsmallest(5, "dist_from_05")[cols] # closest to 0.5 = uncertain

print("most confident: NO pneumothorax (prob. closest to 0)")
print(no_disease.to_string())

print("most confident: pneumothorax (prob. closest to 1)")
print(disease.to_string())

print("least confident (prob. closest to 0.5)")
print(uncertain.to_string())

# no disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest/confidence_images/no_disease

# disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest/confidence_images/disease

# uncertain
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest/confidence_images/uncertain

most confident: NO pneumothorax (prob. closest to 0)
                                                             img_id  y_true                    scanner sex      prob
7100   216840111366964013686042548532013156114347330_02-105-039.png       0  ImagingDynamicsCompanyLtd   F  0.026153
274              103693917093872830847809526276065588596_q5hqnk.png       0  ImagingDynamicsCompanyLtd   F  0.026232
16238  216840111366964012959786098432011039154446686_00-178-047.png       0  ImagingDynamicsCompanyLtd   F  0.028250
16501  216840111366964012487858717522009210154307867_00-030-109.png       0      PhilipsMedicalSystems   F  0.028538
8684   216840111366964013515091760022012320082235519_01-151-073.png       0  ImagingDynamicsCompanyLtd   F  0.028985
most confident: pneumothorax (prob. closest to 1)
                                                             img_id  y_true                    scanner sex      prob
2444             103953050703210888484377088771966492555_pnj9nk.png       1  ImagingDynamicsCompanyLtd   F  0.999151
20967  216840111366964013076187734852011293122719023_00-195-156.png       1      PhilipsMedicalSystems   M  0.999146
21178  216840111366964012922382741642010356134221543_04-000-079.png       1  ImagingDynamicsCompanyLtd   F  0.999091
13203  216840111366964013340662495472012102131826972_01-073-154.png       1  ImagingDynamicsCompanyLtd   F  0.998868
20732  216840111366964012373310883942009159091117491_00-092-146.png       1  ImagingDynamicsCompanyLtd   F  0.998858
least confident (prob. closest to 0.5)
                                                             img_id  y_true                scanner sex      prob
11940  216840111366964013076187734852011173090611529_01-019-081.png       0  PhilipsMedicalSystems   M  0.499996
16068  216840111366964013076187734852011264140425121_00-139-052.png       0  PhilipsMedicalSystems   F  0.500059
14105  216840111366964012558082906712010083112249237_03-153-192.png       0  PhilipsMedicalSystems   M  0.499920
3806            89532200209511112896356230533830256387_2_m7y0a5.png       0  PhilipsMedicalSystems   M  0.500214
17557  216840111366964012558082906712009323115604963_00-107-023.png       1  PhilipsMedicalSystems   F  0.499764

# PadChest (pneumothorax)

In [73]:
padchest_px["prob"] = padchest_px["layer_17"]
padchest_px["dist_from_05"] = (padchest_px["prob"] - 0.5).abs()

cols = ["img_id", "y_true", "scanner", "sex", "prob"]

no_disease = padchest_px.nsmallest(5, "prob")[cols] # closest to 0 = confident no pneumothorax
disease = padchest_px.nlargest(5, "prob")[cols] # closest to 1 = confident pneumothorax
uncertain = padchest_px.nsmallest(5, "dist_from_05")[cols] # closest to 0.5 = uncertain

print("most confident: NO pneumothorax (prob. closest to 0)")
print(no_disease.to_string())

print("most confident: pneumothorax (prob. closest to 1)")
print(disease.to_string())

print("least confident (prob. closest to 0.5)")
print(uncertain.to_string())

# no disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest_px/confidence_images/no_disease

# disease
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest_px/confidence_images/disease

# uncertain
# scp nizp@hpc.itu.dk:/home/data_shares/purrlab/padchest/dir_num/img.png ~/Documents/uni/msc/4_semester/MedCLIP_subgroup/reports/padchest_px/confidence_images/uncertain

most confident: NO pneumothorax (prob. closest to 0)
                                                             img_id  y_true                    scanner sex      prob
17545  216840111366964012558082906712009322124844600_00-107-093.png       0  ImagingDynamicsCompanyLtd   F  0.041576
18735  216840111366964012558082906712009344110636318_00-089-099.png       0  ImagingDynamicsCompanyLtd   F  0.042710
4243             248261555152019367507591328512148732003_yot61b.png       0  ImagingDynamicsCompanyLtd   M  0.044313
114              147036015370488755117195440122198442935_gj6nyv.png       0  ImagingDynamicsCompanyLtd   F  0.046085
1841             208990610239313623398510691329973957149_ttvss6.png       0  ImagingDynamicsCompanyLtd   M  0.048978
most confident: pneumothorax (prob. closest to 1)
                                                             img_id  y_true                scanner sex      prob
8438   216840111366964013590140476722013081090219068_02-051-197.png       0  PhilipsMedicalSystems   M  0.999908
7159   216840111366964013590140476722013073124742612_02-055-150.png       0  PhilipsMedicalSystems   M  0.999858
1486             235635165976594378061468822488815969962_5aqavg.png       0  PhilipsMedicalSystems   M  0.999425
6259   216840111366964013590140476722013071210407803_02-053-116.png       0  PhilipsMedicalSystems   M  0.999179
14541  216840111366964012558082906712010081091913043_03-161-159.png       1  PhilipsMedicalSystems   M  0.998198
least confident (prob. closest to 0.5)
                                                             img_id  y_true                scanner sex      prob
20204  216840111366964012339356563862009055140056025_00-054-109.png       0  PhilipsMedicalSystems   F  0.500051
14073  216840111366964012768025509942010209091203081_03-141-079.png       0  PhilipsMedicalSystems   M  0.499938
18761  216840111366964012989926673512011104123847985_00-191-127.png       0  PhilipsMedicalSystems   M  0.499932
16548  216840111366964013076187734852011200121554317_00-142-013.png       0  PhilipsMedicalSystems   F  0.499925
21219  216840111366964012734950068292010165091230160_04-012-042.png       0  PhilipsMedicalSystems   F  0.499889

# Bins

In [74]:
bins = [0, 0.5, 0.8, 0.9, 0.95, 0.99, 1.01]
print(chestx["prob"].value_counts(bins=bins, sort=False))

(-0.001, 0.5]     7163
(0.5, 0.8]       10381
(0.8, 0.9]        3350
(0.9, 0.95]       2110
(0.95, 0.99]      2088
(0.99, 1.01]       504
Name: count, dtype: int64

# ___________________________________________________________________________________________

In [75]:
df_padchest = pd.read_csv("../data/processed/padchest/processed_labels.csv")

In [76]:
df_padchest.head()

,ImageID,ImageDir,StudyDate_DICOM,StudyID,PatientID,PatientBirth,PatientSex_DICOM,ViewPosition_DICOM,Projection,MethodProjection,Pediatric,Modality_DICOM,Manufacturer_DICOM,PhotometricInterpretation_DICOM,PixelRepresentation_DICOM,PixelAspectRatio_DICOM,SpatialResolution_DICOM,BitsStored_DICOM,WindowCenter_DICOM,WindowWidth_DICOM,Rows_DICOM,Columns_DICOM,XRayTubeCurrent_DICOM,Exposure_DICOM,ExposureInuAs_DICOM,ExposureTime,RelativeXRayExposure_DICOM,ReportID,Report,MethodLabel,Labels,Localizations,LabelsLocalizationsBySentence,labelCUIS,LocalizationsCUIS,study_year,age,target_label
0,20536686640136348236148679891455886468_k6ga29.png,0,15-09-2014,20536686640136348236148679891455886468,839860488694292331637988235681460987,1930,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2092.0,2251.0,1728,1872,250.0,2.0,2500.0,10.0,-1.42,4765777,sin hallazg patolog edad pacient .,Physician,['normal'],[],"[['normal'], ['normal']]",[],[],2014,84,0
1,135803415504923515076821959678074435083_fzis7b...,0,14-09-2015,135803415504923515076821959678074435083,313572750430997347502932654319389875966,1929,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2155.0,2880.0,3572,3732,320.0,3.0,3200.0,10.0,NaN,4991845,cambi pulmonar cronic sever . sign fibrosis b...,Physician,"['pulmonary fibrosis', 'kyphosis', 'ground gla...","['loc basal', 'loc basal bilateral']","[['pulmonary fibrosis', 'loc basal bilateral']...",['C0034069' 'C0742362' 'C2115817' 'C3544344'],['C1282378'],2015,86,0
2,113855343774216031107737439268243531979_3k951l...,0,17-07-2015,113855343774216031107737439268243531979,50783093527901818115346441867348318648,1925,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2472.0,2325.0,3584,3240,400.0,3.0,3200.0,8.0,NaN,4955977,. . siluet cardi mediastin dentr normal . cam...,Physician,['chronic changes'],"['loc cardiac', 'loc mediastinum', 'loc costop...","[['chronic changes'], ['chronic changes'], ['n...",['C0742362'],['C1522601' 'C0025066' 'C0230151'],2015,90,0
3,313903302629300007485735352869488750471_75sg0k...,0,25-01-2017,313903302629300007485735352869488750471,3707275269754751392247446521222810702,1978,M,NaN,AP,Manual review of DICOM fields,No,CR,PhilipsMedicalSystems,MONOCHROME2,0,"['1', '1']",0.200,12,2047.0,4095.0,1760,2140,NaN,NaN,NaN,NaN,1192.00,5310833,objet mejori radiolog con practic resolucion ...,Physician,"['interstitial pattern', 'alveolar pattern', '...","['loc basal', 'loc left']","[['unchanged'], ['alveolar pattern', 'intersti...",['C1332240' 'C2073538'],['C1282378' 'C0443246'],2017,39,0
4,3137231742710829928-247610802266403640553_kine...,0,04-08-2015,3137231742710829928-247610802266403640553,93535126770783451980359712286922420997,1957,M,NaN,PA,Manual review of DICOM fields,No,CR,PhilipsMedicalSystems,MONOCHROME2,0,"['1', '1']",0.143,12,2047.0,4095.0,2968,2973,0.0,0.0,NaN,0.0,299.00,4969767,radiografi actual comp con previ 26 juni pers...,Physician,"['laminar atelectasis', 'sternotomy', 'pleural...","['loc basal', 'loc subsegmental', 'loc pleural...","[['laminar atelectasis', 'loc subsegmental', '...",['C2073625' 'C4305366' 'C0185792'],['C1282378' 'C0929165' 'C0032225' 'C0444532' '...,2015,58,0

In [79]:
drains_pivot_test = (df_padchest.explode("Manufacturer_DICOM").pivot_table(index="Manufacturer_DICOM", columns="study_year", 
                                   aggfunc="size", fill_value=0))
drains_pivot_test

study_year,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Manufacturer_DICOM,,,,,,,,,,,
ImagingDynamicsCompanyLtd,13,31,9996,8621,8164,9016,9113,6184,2966,244,0
PhilipsMedicalSystems,3,2,4965,6555,7688,6929,5932,5140,4319,6925,5288

In [82]:
df_padchest[(df_padchest["study_year"] == 2007) & (df_padchest["Manufacturer_DICOM"] == "ImagingDynamicsCompanyLtd")]

,ImageID,ImageDir,StudyDate_DICOM,StudyID,PatientID,PatientBirth,PatientSex_DICOM,ViewPosition_DICOM,Projection,MethodProjection,Pediatric,Modality_DICOM,Manufacturer_DICOM,PhotometricInterpretation_DICOM,PixelRepresentation_DICOM,PixelAspectRatio_DICOM,SpatialResolution_DICOM,BitsStored_DICOM,WindowCenter_DICOM,WindowWidth_DICOM,Rows_DICOM,Columns_DICOM,XRayTubeCurrent_DICOM,Exposure_DICOM,ExposureInuAs_DICOM,ExposureTime,RelativeXRayExposure_DICOM,ReportID,Report,MethodLabel,Labels,Localizations,LabelsLocalizationsBySentence,labelCUIS,LocalizationsCUIS,study_year,age,target_label
80560,216840111366964011834620052302007193132734181_...,37,12-07-2007,216840111366964011834620052302007193132734181,71157216424705523469305871710896328689,1949,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1980.0,2490.0,1848,1960,250.0,2.0,2500.0,10.0,-1.82,3247120,sin alter .,RNN_model,['normal'],[],['normal'],[],[],2007,58,0
80573,216840111366964011773332489982007165104219430_...,37,19-06-2007,216840111366964011773332489982007165104219430,296259705639859029692000520892386685795,1937,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1976.0,2219.0,1516,1800,250.0,2.0,2500.0,10.0,-1.37,3231176,sin hallazg signific .,RNN_model,['normal'],[],['normal'],[],[],2007,70,0
80595,216840111366964011834620052302007218115747729_...,37,07-08-2007,216840111366964011834620052302007218115747729,131287027041939583121820962437959170413,1926,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2341.0,2861.0,1672,1772,320.0,3.0,3200.0,10.0,-1.88,3259784,torax senil .,RNN_model,['normal'],[],['normal'],[],[],2007,81,0
80608,216840111366964011920393606282007324111641950_...,37,21-11-2007,216840111366964011920393606282007324111641950,48864201671639101800997404272912563556,1974,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1929.0,2576.0,1840,1896,250.0,2.0,2500.0,10.0,-2.26,3314347,dentr normal .,RNN_model,['normal'],[],['normal'],[],[],2007,33,0
80609,216840111366964011960822759732007331120820383_...,37,27-11-2007,216840111366964011960822759732007331120820383,268834365529208063585967283645474674568,1933,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1918.0,2157.0,1660,1960,320.0,3.0,3200.0,10.0,-1.32,3318611,cifosis sign osteoporosis acun cuerp vertebra...,RNN_model,"['fibrotic band', 'kyphosis', 'callus rib frac...","['loc left', 'loc lobar', 'loc posterior rib',...","['kyphosis', ' osteoporosis', ' vertebral ante...",['C2115817' 'C0029456' 'C0006767' 'C0865843' '...,['C0443246' 'C0225752' 'C4323265' 'C0035561' '...,2007,74,0
80611,216840111366964011773332489982007149112324799_...,37,31-05-2007,216840111366964011773332489982007149112324799,258474666184536032664921197460462041046,1944,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1937.0,2612.0,1972,2000,250.0,2.0,2500.0,10.0,-2.11,3221705,radiografi posteroanterior preoperatori pinza...,RNN_model,"['costophrenic angle blunting', 'nodule', 'alv...","['loc middle lung field', 'loc left costophren...","['costophrenic angle blunting', 'loc left cost...",['C0742855' 'C1332240' 'C2073538' 'C0034079' ''],['C0929434' 'C0504100' 'C0225756' 'C0444532' '...,2007,63,0
80621,216840111366964011920393606282007317100358109_...,37,15-11-2007,216840111366964011920393606282007317100358109,313792356433060858464422353977507833247,1941,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2118.0,2527.0,1628,1704,250.0,2.0,2500.0,10.0,-1.84,3309779,densidad lineal proyect bas izquierd probabl ...,RNN_model,['increased density'],"['loc left', 'loc basal']","['increased density', 'loc left', 'loc basal']",['C1443940'],['C0443246' 'C1282378'],2007,66,0
80624,216840111366964011920393606282007323141114422_...,37,22-11-2007,216840111366964011920393606282007323141114422,318583107281615176392254487090230564424,1932,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2164.0,2174.0,1832,2000,500.0,12.0,12500.0,25.0,1.02,3313803,marc deform par torac izquierd valor antecede...,RNN_model,[],['loc left'],"['', 'loc left']",[''],['C0443246'],2007,75,0
80633,216840111366964011885741831142007246100641368_...,37,04-09-2007,216840111366964011885741831142007246100641368,254529899889786282798766412556382019416,1933,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1827.0,2191.0,1756,1680,500.0,2.0,2500.0,5.0,-1.25,3272231,. . sin hallazg signific .,RNN_model,['normal'],[],['normal'],[],[],2007,74,0
80644,216840111366964011834620052302007198143148595_...,37,20-07-2007,216840111366964011834620052302007198143148595,323685823501567270251756965309820004751,1947,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1798.0,2372.0,1816,1840,250.0,2.0,2500.0,10.0,-1.06,3249695,compar con estudi previ juni sin observ cambi...,RNN_model,"['surgery lung', 'copd signs', 'unchanged']","['loc hemithorax', 'loc aortic button', 'loc r...","['unchanged', 'surgery lung', 'loc hemithorax'...",['C0038903' '' 'C0024117'],['C0934569' 'C0003489' 'C0444532'],2007,60,0
80647,216840111366964011773332489982007123101900812_...,37,11-06-2007,216840111366964011773332489982007123101900812,173818646875604183371976194412244844419,1951,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1881.0,2346.0,1736,1644,250.0,2.0,2500.0,10.0,-0.32,3206031,motiv epoc tac adenopati 1 5 hili derech atel...,RNN_model,"['nipple shadow', 'adenopathy', 'pseudonodule'...","['loc middle lung field', 'loc nipple', 'loc r...","['', 'loc lobar', 'loc hilar', 'loc right', 'C...",['' 'C0024117' 'C0478664'],['C0929434' 'C0028109' 'C0444532' 'C0225752' '...,2007,56,0
80671,216840111366964011773332489982007120083858078_...,37,03-05-2007,216840111366964011773332489982007120083858078,181643375540706419890412412131731939999,1940,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,1951.0,1749.0,1832,2000,320.0,3.0,3200.0,10.0,-0.46,3204232,identific dos pequen infiltr pulmonar mal def...,RNN_model,"['infiltrates', 'pneumonia']","['loc right lower lobe', 'loc lingula', 'loc b...","['infiltrates', ' pneumonia', 'loc right lower...",['C0277877' 'C0032285'],['C1261075' 'C0225740' 'C1282378' 'C0006255'],2007,67,0
80676,216840111366964011920393606282007317125403605_...,37,16-11-2007,216840111366964011920393606282007317125403605,296259705639859029692000520892386685795,1937,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2127.0,2389.0,1592,1476,250.0,2.0,2500.0,10.0,-1.82,3310073,escoliosis dorsal .,RNN_model,['scoliosis'],[],['scoliosis'],['C0036439'],[],2007,70,0

In [83]:
df_padchest[(df_padchest["study_year"] == 2016) & (df_padchest["Manufacturer_DICOM"] == "ImagingDynamicsCompanyLtd")]

,ImageID,ImageDir,StudyDate_DICOM,StudyID,PatientID,PatientBirth,PatientSex_DICOM,ViewPosition_DICOM,Projection,MethodProjection,Pediatric,Modality_DICOM,Manufacturer_DICOM,PhotometricInterpretation_DICOM,PixelRepresentation_DICOM,PixelAspectRatio_DICOM,SpatialResolution_DICOM,BitsStored_DICOM,WindowCenter_DICOM,WindowWidth_DICOM,Rows_DICOM,Columns_DICOM,XRayTubeCurrent_DICOM,Exposure_DICOM,ExposureInuAs_DICOM,ExposureTime,RelativeXRayExposure_DICOM,ReportID,Report,MethodLabel,Labels,Localizations,LabelsLocalizationsBySentence,labelCUIS,LocalizationsCUIS,study_year,age,target_label
171,150762056036635610657089202556643673250_rczqej...,0,12-01-2016,150762056036635610657089202556643673250,116003495541864449748431699985618985287,1965,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2227.0,2670.0,3376,3628,400.0,4.0,4000.0,10.0,NaN,5061499,. sin hallazg .,Physician,['normal'],[],"[['normal'], ['normal']]",[],[],2016,51,0
278,222462790575669844431021710120156553492-2_ijn0...,0,04-01-2016,222462790575669844431021710120156553492-2,108691879884374090569372186333435248359,1956,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2380.0,2702.0,3452,3560,320.0,3.0,3200.0,10.0,NaN,5059329,no observ consolid infiltr . bull camp pulmon...,Physician,"['bullas', 'unchanged']","['loc lung field', 'loc middle lung field', 'l...","[['normal'], ['bullas', 'loc lung field', 'loc...",['C0241982'],['C0225759' 'C0929434' 'C0444532'],2016,60,0
341,144478523611315461003350014835868422251_2_s8dl...,0,05-01-2016,144478523611315461003350014835868422251_2,156300439407232439460684790908276892962,1939,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2486.0,2934.0,3160,3648,320.0,3.0,3200.0,10.0,NaN,5058044,. . no dat contraindiqu cirugi punt vist imag,Physician,['normal'],[],[['normal']],[],[],2016,77,0
383,146556660707431499811175451504272713520_qcraax...,0,13-01-2016,146556660707431499811175451504272713520,263096109266749373099664379841268764529,1957,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2149.0,2808.0,3160,3324,400.0,4.0,4000.0,10.0,NaN,4955079,sin hallazg,Physician,['normal'],[],"[['normal'], ['normal']]",[],[],2016,59,0
448,30730032960553671408628043661008406988_2t8qli.png,0,12-01-2016,30730032960553671408628043661008406988,178087749213987617339751516085396869774,1955,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2286.0,2670.0,2976,3628,400.0,4.0,4000.0,10.0,NaN,5060800,. elevacion hemidiafragm anterior derech . el...,Physician,"['hemidiaphragm elevation', 'scoliosis', 'incr...","['loc diaphragm', 'loc paracardiac', 'loc aort...","[['aortic elongation', 'loc aortic'], ['increa...",['C1443940' 'C0036439' 'C2073707'],['C0011980' 'C0003483' 'C0444532' 'C0443246'],2016,61,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25455,1615287941156745557157829298884441530_hxajwo.png,54,11-01-2016,1615287941156745557157829298884441530,14791510884648819256050071767077326865,1966,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2193.0,2961.0,3508,3244,400.0,3.0,3200.0,8.0,NaN,5060994,sin hallazg relev .,Physician,['normal'],[],[['normal']],[],[],2016,50,0
25636,198117630279442083542714100636577220720_voyvpt...,54,16-02-2016,198117630279442083542714100636577220720,119391983665152364706585221017503730159,1961,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2482.0,2341.0,3684,3308,320.0,3.0,3200.0,10.0,NaN,5088802,sign radiolog epoc . call fractur parrill cos...,Physician,"['callus rib fracture', 'copd signs']","['loc rib', 'loc right']","[['COPD signs'], ['COPD signs'], ['COPD signs'...",['C0024117' 'C0006767'],['C0035561' 'C0444532'],2016,55,0
25726,262022733994578421456872020303541709896_fmvasg...,12,11-01-2016,262022733994578421456872020303541709896,149666042494515812550354988099556433149,1955,M,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2290.0,2872.0,3444,3684,400.0,4.0,4000.0,10.0,NaN,5061002,sin hallazg relev .,Physician,['normal'],[],[['normal']],[],[],2016,61,0
25753,128461969111859531196412937129493857827_dtop85...,12,14-01-2016,128461969111859531196412937129493857827,79533098068101099820740123033722336734,1942,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2183.0,2869.0,2940,3160,400.0,4.0,4000.0,10.0,NaN,5064726,. torax enfisemat,Physician,['emphysema'],[],[['emphysema']],['C0034067'],[],2016,74,0
25937,213445691747815952630459728817015978901_pfn5yo...,12,16-02-2016,213445691747815952630459728817015978901,90197935862856112361202187409248836575,1945,F,POSTEROANTERIOR,PA,Manual review of DICOM fields,No,CR,ImagingDynamicsCompanyLtd,MONOCHROME2,0,NaN,NaN,12,2340.0,2751.0,3356,3424,400.0,3.0,3200.0,8.0,NaN,5088495,no observ consolid lesion sospech . cambi mec...,Physician,['vertebral degenerative changes'],['loc column'],"[['vertebral degenerative changes', 'loc colum...",['C4290224'],['C0037949'],2016,71,0