In [19]:
import pandas as pd
from sklearn.metrics import roc_auc_score, accuracy_score

In [20]:
df_calibration = pd.read_csv("../reports/chestx/drain/calibration_drain.csv")
df_calibration_padchest = pd.read_csv("../reports/padchest/padchest_scanner/calibration_scanner.csv")

In [21]:
df_calibration.head()

   y_true    y_prob  drain
0       0  0.514142      0
1       0  0.687464      0
2       0  0.813720      0
3       0  0.508774      0
4       0  0.723479      0

# drain

In [22]:
y_true = df_calibration["y_true"]
y_prob = df_calibration["y_prob"]
drain = df_calibration["drain"]
# sex = df_calibration["sex"]

In [23]:
df_calibration["y_pred"] = (df_calibration["y_prob"]).astype(int)
y_pred = df_calibration["y_pred"]

In [24]:
auroc = roc_auc_score(y_true=y_true, y_score=y_prob)
auroc

0.8386699457210035

In [25]:
accuracy = accuracy_score(y_true=y_true, y_pred=y_pred)
accuracy

0.8958821690889202

# PadChest scanner

In [26]:
df_calibration_padchest.head()

   y_true    y_prob                    scanner
0       0  0.227102      PhilipsMedicalSystems
1       0  0.139315      PhilipsMedicalSystems
2       0  0.287729  ImagingDynamicsCompanyLtd
3       0  0.268475      PhilipsMedicalSystems
4       0  0.155133      PhilipsMedicalSystems

In [27]:
y_true_p = df_calibration_padchest["y_true"]
y_prob_p = df_calibration_padchest["y_prob"]
scanner = df_calibration_padchest["scanner"]
# sex = df_calibration_padchest["sex"]

In [28]:
df_calibration_padchest["y_pred"] = (df_calibration_padchest["y_prob"]).astype(int)
y_pred_p = df_calibration_padchest["y_pred"]

In [29]:
auroc_p = roc_auc_score(y_true=y_true_p, y_score=y_prob_p)
auroc_p

0.9050495971229963

In [30]:
accuracy_p = accuracy_score(y_true=y_true_p, y_pred=y_pred_p)
accuracy_p

0.9142857142857143